In [5]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

In [6]:
res = requests.get('https://quotes.toscrape.com')
soup = BeautifulSoup(res.text, 'html.parser')

In [7]:
for page in range(2,11):
    link = "https://quotes.toscrape.com/page/" + str(page) + '/'
    res = requests.get(link)
    soup = BeautifulSoup(res.text, 'html.parser')

    for sp in soup.find_all('div', class_ = 'quote'):
        quote      = sp.find('span', class_ = 'text').text[1 : -1] 
        author     = sp.find('small').text
        author_id  = sp.find('a').get('href')

        tags = []
        for tag in sp.find_all('a', class_ = 'tag'):
            tags.append(tag.text)
        tags = ','.join(tags)

In [14]:
data = []
for page in tqdm(range(1,11)):
    link = "https://quotes.toscrape.com/page/" + str(page) + '/'
    res = requests.get(link)
    soup = BeautifulSoup(res.text, 'html.parser')

    for sp in soup.find_all('div', class_ = 'quote'):
        quote      = sp.find('span', class_ = 'text').text[1 : -1] 
        author     = sp.find('small').text
        author_id  = sp.find('a').get('href')

        tags = []
        for tag in sp.find_all('a', class_ = 'tag'):
            tags.append(tag.text)
        tags = ','.join(tags)

        data.append([quote, author, author_id, tags])

100%|███████████████████████████████████████████| 10/10 [00:16<00:00,  1.67s/it]

In [15]:
df = pd.DataFrame(data, columns = ['quote', 'author', 'author_id', 'tags'])

In [21]:
df.to_csv('Quotes.csv', index = False)

In [17]:
df

,quote,author,author_id,tags
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices"
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational"
...,...,...,...,...
95,You never really understand a person until you...,Harper Lee,/author/Harper-Lee,better-life-empathy
96,You have to write the book that wants to be wr...,Madeleine L'Engle,/author/Madeleine-LEngle,"books,children,difficult,grown-ups,write,write..."
97,Never tell the truth to people who are not wor...,Mark Twain,/author/Mark-Twain,truth
98,"A person's a person, no matter how small.",Dr. Seuss,/author/Dr-Seuss,inspirational
99,... a mind needs books as a sword needs a whet...,George R.R. Martin,/author/George-R-R-Martin,"books,mind"

In [19]:
df['author_id link'] = 'https://quotes.toscrape.com' + df['author_id']

In [20]:
df

,quote,author,author_id,tags,author_id link
0,The world as we have created it is a process o...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world",https://quotes.toscrape.com/author/Albert-Eins...
1,"It is our choices, Harry, that show what we tr...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices",https://quotes.toscrape.com/author/J-K-Rowling
2,There are only two ways to live your life. One...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles",https://quotes.toscrape.com/author/Albert-Eins...
3,"The person, be it gentleman or lady, who has n...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor",https://quotes.toscrape.com/author/Jane-Austen
4,"Imperfection is beauty, madness is genius and ...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational",https://quotes.toscrape.com/author/Marilyn-Monroe
...,...,...,...,...,...
95,You never really understand a person until you...,Harper Lee,/author/Harper-Lee,better-life-empathy,https://quotes.toscrape.com/author/Harper-Lee
96,You have to write the book that wants to be wr...,Madeleine L'Engle,/author/Madeleine-LEngle,"books,children,difficult,grown-ups,write,write...",https://quotes.toscrape.com/author/Madeleine-L...
97,Never tell the truth to people who are not wor...,Mark Twain,/author/Mark-Twain,truth,https://quotes.toscrape.com/author/Mark-Twain
98,"A person's a person, no matter how small.",Dr. Seuss,/author/Dr-Seuss,inspirational,https://quotes.toscrape.com/author/Dr-Seuss
99,... a mind needs books as a sword needs a whet...,George R.R. Martin,/author/George-R-R-Martin,"books,mind",https://quotes.toscrape.com/author/George-R-R-...